import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ar' | 'pt' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.chapters': 'Chapters',
    'nav.about': 'About',
    'nav.download': 'Download PDF',
    
    // Hero
    'hero.title': "The Parliamentarians' Global Guide to Climate Change and Climate Solutions",
    'hero.subtitle': 'Essential knowledge for policymakers navigating the climate crisis',
    'hero.cta': 'Explore Chapters',
    'hero.scroll': 'Scroll to learn more',
    
    // Youth Foreword
    'youth.title': 'Youth Foreword',
    'youth.authoredBy': 'Youth Foreword authored by',
    'youth.quote1': 'As young people, we often look to our elders for guidance. From you, we develop our values, our ethics, and our worldview. We owe you our opportunities and privileges. We share your values of security, prosperity, and opportunity.',
    'youth.quote2': "But it's a strange time to be young. \"Go to school, get a job, work towards your future\". We wonder, what will our futures look like?",
    'youth.content1': 'The 1.5°C threshold is passing, 2.0°C is fast approaching. We call on you to follow through on the climate goals that you set, to be transparent and accountable. Our futures are at stake.',
    'youth.content2': 'Human well-being depends on planetary health. Indigenous wisdoms have maintained for millennia the belief that humanity and the natural world are intimately connected. Our futures depend upon combining these ancient wisdoms with modern day technological capabilities, environmental stewardship, and a decisive political will.',
    'youth.content3': 'The science is clear. The technologies exist. The challenge that remains is a lack of implementation. The IMF estimates there is an astounding $7.1 trillion per annum in fossil fuel subsidies. We need new economic structures and incentives to scale global solutions, and we need to act now. This is no longer a distant warning, we are living in the age of consequence.',
    'youth.content4': 'The International Court of Justice is on our side, affirming what young people across the globe have been saying for years: our governments have a legal obligation to act on climate change. As the current leaders and policymakers, we require your brave and authentic leadership to navigate this age of complexity and uncertainty, to chart a sustainable path forward.',
    'youth.content5': 'This must be done together, across disciplines, countries, genders, and generations.',
    'youth.content6': 'One concrete step parties can take to align international commitments with intergenerational justice is to adopt the Universal Youth Clause into their updated Nationally Determined Contributions. We call on all governments to honour our right to a healthy environment and a climate just future for generations to come.',
    'youth.closingQuote': 'As young people, we often look to our elders for guidance. Do they know that they can look to us, too?',
    'youth.endorsersNote': 'Endorsers of the Youth Foreword can be found on page 26.',
    'youth.scanForMore': 'Scan for more info',
    'youth.learnMore': 'Learn more about the Youth Foreword and endorsers',
    'youth.imfEstimates': 'The IMF estimates',
    'youth.imfAmount': '$7.1 trillion/year',
    'youth.imfSubsidies': 'in fossil fuel subsidies',
    
    // Chapters
    'chapters.title': 'Chapters',
    'chapters.subtitle': 'A comprehensive guide across 10 essential topics',
    
    // Chapter Titles
    'chapter1.title': 'Fundamentals of Climate Change',
    'chapter1.desc': 'We have known for more than 100 years that carbon dioxide and methane are greenhouse gases which trap energy within the Earth\'s atmosphere.',
    'chapter2.title': 'Nature and Biodiversity Loss',
    'chapter2.desc': 'Halting the loss of ecosystems will both help protect the biodiversity they contain and retain their role as carbon sinks.',
    'chapter3.title': 'Poles and Oceans',
    'chapter3.desc': 'The polar regions are in crisis. These beautiful places might seem remote, but the poles are the control centre for our climate system.',
    'chapter4.title': 'Adaptation',
    'chapter4.desc': 'Adaptation is the increasingly vital second line of defence in the climate crisis, but finance is lacking and implementation of current plans is uneven.',
    'chapter5.title': 'Climate Finance',
    'chapter5.desc': 'Almost half of humanity – 3.4 billion people – live in countries now spending more on debt servicing than education and health. We must lay the foundation for unlocking long-term, affordable financing to enable sustainable development. ',
    'chapter6.title': 'The Economics of Climate Change',
    'chapter6.desc': 'It is clearer than ever that the costs of inaction on climate change will be far greater than the investments required to make the transition to a sustainable, inclusive and resilient global economy. ',
    'chapter7.title': 'Energy, Transport and Industry Transition',
    'chapter7.desc': 'Outdated conventional wisdom suggests the low-carbon transition will be more expensive than fossil fuels. There is a better way. ',
    'chapter8.title': 'Food, Forests and Fisheries',
    'chapter8.desc': 'We produce enough food for 10 billion people – yet a third of all food is wasted, and 800 million people remain hungry.',
    'chapter9.title': 'COP – Do Your Constituents Care?',
    'chapter9.desc': 'When the Paris Agreement was adopted in 2015, our planet was on track to warm by nearly 5°C. Today, it\'s on track to warm by nearly 3°C.',
    'chapter10.title': 'Carbon Capture and Carbon Markets',
    'chapter10.desc': 'All options must be on the table, but technical solutions will be needed to cope with the formidable scale of necessary carbon removal.',
    
    // Stats
    'stat.temperature': '1.5°C',
    'stat.temperature.label': 'Paris Agreement threshold',
    'stat.subsidies': '$7.1T',
    'stat.subsidies.label': 'Annual fossil fuel subsidies',
    'stat.support': '89%',
    'stat.support.label': 'Want more climate action',
    
    // Footer
    'footer.attribution': 'Chapter Attribution',
    'footer.endorsers': 'Youth Foreword Endorsers',
    'footer.copyright': '© 2025 Parliamentarians Climate Guide',
    
    // Common
    'common.readMore': 'Read More',
    'common.learnMore': 'Learn More',
    'common.keyFacts': 'Key Facts',
    'common.takeAction': 'Take Action',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.chapters': 'Capítulos',
    'nav.about': 'Acerca de',
    'nav.download': 'Descargar PDF',
    'hero.title': 'Guía Global de Parlamentarios sobre el Cambio Climático y Soluciones Climáticas',
    'hero.subtitle': 'Conocimiento esencial para los responsables políticos que enfrentan la crisis climática',
    'hero.cta': 'Explorar Capítulos',
    'hero.scroll': 'Desplácese para saber más',
    'youth.title': 'Prólogo de la Juventud',
    'youth.authoredBy': 'Prólogo de la Juventud escrito por',
    'youth.quote1': 'Como jóvenes, a menudo buscamos la guía de nuestros mayores. De ustedes desarrollamos nuestros valores, nuestra ética y nuestra visión del mundo. Les debemos nuestras oportunidades y privilegios. Compartimos sus valores de seguridad, prosperidad y oportunidad.',
    'youth.quote2': 'Pero es un momento extraño para ser joven. "Ve a la escuela, consigue un trabajo, trabaja para tu futuro". Nos preguntamos, ¿cómo serán nuestros futuros?',
    'youth.content1': 'El umbral de 1.5°C está pasando, 2.0°C se acerca rápidamente. Les pedimos que cumplan con los objetivos climáticos establecidos, que sean transparentes y responsables. Nuestro futuro está en juego.',
    'youth.content2': 'El bienestar humano depende de la salud planetaria. Las sabidurías indígenas han mantenido durante milenios la creencia de que la humanidad y el mundo natural están íntimamente conectados. Nuestros futuros dependen de combinar estas antiguas sabidurías con las capacidades tecnológicas modernas, la administración ambiental y una voluntad política decisiva.',
    'youth.content3': 'La ciencia es clara. Las tecnologías existen. El desafío que queda es la falta de implementación. El FMI estima que hay asombrosos $7.1 billones anuales en subsidios a combustibles fósiles. Necesitamos nuevas estructuras económicas e incentivos para escalar soluciones globales, y necesitamos actuar ahora. Esto ya no es una advertencia lejana, estamos viviendo en la era de las consecuencias.',
    'youth.content4': 'La Corte Internacional de Justicia está de nuestro lado, afirmando lo que los jóvenes de todo el mundo han estado diciendo durante años: nuestros gobiernos tienen la obligación legal de actuar sobre el cambio climático. Como líderes y formuladores de políticas actuales, requerimos su liderazgo valiente y auténtico para navegar esta era de complejidad e incertidumbre, para trazar un camino sostenible hacia adelante.',
    'youth.content5': 'Esto debe hacerse juntos, a través de disciplinas, países, géneros y generaciones.',
    'youth.content6': 'Un paso concreto que las partes pueden tomar para alinear los compromisos internacionales con la justicia intergeneracional es adoptar la Cláusula Universal de la Juventud en sus Contribuciones Determinadas a Nivel Nacional actualizadas. Hacemos un llamado a todos los gobiernos para que honren nuestro derecho a un medio ambiente saludable y un futuro climático justo para las generaciones venideras.',
    'youth.closingQuote': 'Como jóvenes, a menudo buscamos la guía de nuestros mayores. ¿Saben ellos que también pueden mirarnos a nosotros?',
    'youth.endorsersNote': 'Los patrocinadores del Prólogo de la Juventud se pueden encontrar en la página 26.',
    'youth.scanForMore': 'Escanea para más información',
    'youth.learnMore': 'Aprende más sobre el Prólogo de la Juventud y patrocinadores',
    'youth.imfEstimates': 'El FMI estima',
    'youth.imfAmount': '$7.1 billones/año',
    'youth.imfSubsidies': 'en subsidios a combustibles fósiles',
    'chapters.title': 'Capítulos',
    'chapters.subtitle': 'Una guía completa a través de 10 temas esenciales',
    'chapter1.title': 'Fundamentos del Cambio Climático',
    'chapter1.desc': 'Comprender la ciencia detrás del cambio climático, los gases de efecto invernadero y por qué importa la tasa de cambio.',
    'chapter2.title': 'Naturaleza y Pérdida de Biodiversidad',
    'chapter2.desc': 'Cómo la biodiversidad sostiene las economías y los medios de vida, y la necesidad urgente de protección.',
    'chapter3.title': 'Polos y Océanos',
    'chapter3.desc': 'El Ártico y la Antártida como centros de control climático, y la triple amenaza que enfrentan nuestros océanos.',
    'chapter4.title': 'Adaptación',
    'chapter4.desc': 'Construir resiliencia y limitar el daño de los impactos climáticos inevitables.',
    'chapter5.title': 'Financiamiento Climático',
    'chapter5.desc': 'Financiando la transición: subsidios, inversiones y el camino hacia el desarrollo sostenible.',
    'chapter6.title': 'La Economía del Cambio Climático',
    'chapter6.desc': 'Estructuras económicas, incentivos y el verdadero costo de la inacción.',
    'chapter7.title': 'Transición Energética, de Transporte e Industrial',
    'chapter7.desc': 'Transformando sectores clave para un futuro bajo en carbono.',
    'chapter8.title': 'Alimentos, Bosques y Pesca',
    'chapter8.desc': 'Sistemas alimentarios sostenibles y la protección de ecosistemas vitales.',
    'chapter9.title': 'COP – ¿Les Importa a Sus Electores?',
    'chapter9.desc': 'Cooperación internacional, educación climática y combate a la desinformación.',
    'chapter10.title': 'Captura de Carbono y Mercados de Carbono',
    'chapter10.desc': 'Soluciones tecnológicas y mecanismos de mercado para lograr cero neto.',
    'stat.temperature': '1.5°C',
    'stat.temperature.label': 'Umbral del Acuerdo de París',
    'stat.subsidies': '$7.1B',
    'stat.subsidies.label': 'Subsidios anuales a combustibles fósiles',
    'stat.support': '89%',
    'stat.support.label': 'Quieren más acción climática',
    'footer.attribution': 'Atribución de Capítulos',
    'footer.endorsers': 'Endosantes del Prólogo Juvenil',
    'footer.copyright': '© 2025 Guía Climática para Parlamentarios',
    'common.readMore': 'Leer Más',
    'common.learnMore': 'Saber Más',
    'common.keyFacts': 'Datos Clave',
    'common.takeAction': 'Tomar Acción',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.chapters': 'Chapitres',
    'nav.about': 'À propos',
    'nav.download': 'Télécharger PDF',
    'hero.title': 'Guide Mondial des Parlementaires sur le Changement Climatique et les Solutions Climatiques',
    'hero.subtitle': 'Connaissances essentielles pour les décideurs face à la crise climatique',
    'hero.cta': 'Explorer les Chapitres',
    'hero.scroll': 'Faites défiler pour en savoir plus',
    'youth.title': 'Avant-propos de la Jeunesse',
    'youth.authoredBy': 'Avant-propos de la Jeunesse rédigé par',
    'youth.quote1': 'En tant que jeunes, nous nous tournons souvent vers nos aînés pour être guidés. De vous, nous développons nos valeurs, notre éthique et notre vision du monde. Nous vous devons nos opportunités et privilèges. Nous partageons vos valeurs de sécurité, de prospérité et d\'opportunité.',
    'youth.quote2': 'Mais c\'est une époque étrange pour être jeune. "Va à l\'école, trouve un emploi, travaille pour ton avenir". Nous nous demandons, à quoi ressembleront nos futurs?',
    'youth.content1': 'Le seuil de 1,5°C est en train d\'être franchi, 2,0°C approche rapidement. Nous vous appelons à respecter les objectifs climatiques fixés, à être transparents et responsables. Nos futurs sont en jeu.',
    'youth.content2': 'Le bien-être humain dépend de la santé planétaire. Les sagesses autochtones maintiennent depuis des millénaires la croyance que l\'humanité et le monde naturel sont intimement liés. Nos futurs dépendent de la combinaison de ces anciennes sagesses avec les capacités technologiques modernes, la gestion environnementale et une volonté politique décisive.',
    'youth.content3': 'La science est claire. Les technologies existent. Le défi qui reste est un manque de mise en œuvre. Le FMI estime qu\'il y a un stupéfiant 7,1 billions de dollars par an en subventions aux combustibles fossiles. Nous avons besoin de nouvelles structures économiques et d\'incitations pour développer des solutions mondiales, et nous devons agir maintenant. Ce n\'est plus un avertissement lointain, nous vivons à l\'ère des conséquences.',
    'youth.content4': 'La Cour internationale de Justice est de notre côté, affirmant ce que les jeunes du monde entier disent depuis des années : nos gouvernements ont l\'obligation légale d\'agir sur le changement climatique. En tant que dirigeants et décideurs actuels, nous avons besoin de votre leadership courageux et authentique pour naviguer cette ère de complexité et d\'incertitude, pour tracer une voie durable vers l\'avant.',
    'youth.content5': 'Cela doit être fait ensemble, à travers les disciplines, les pays, les genres et les générations.',
    'youth.content6': 'Une étape concrète que les parties peuvent prendre pour aligner les engagements internationaux avec la justice intergénérationnelle est d\'adopter la Clause universelle de la jeunesse dans leurs Contributions déterminées au niveau national mises à jour. Nous appelons tous les gouvernements à honorer notre droit à un environnement sain et un avenir climatique juste pour les générations à venir.',
    'youth.closingQuote': 'En tant que jeunes, nous nous tournons souvent vers nos aînés pour être guidés. Savent-ils qu\'ils peuvent aussi se tourner vers nous?',
    'youth.endorsersNote': 'Les signataires de l\'Avant-propos de la Jeunesse se trouvent à la page 26.',
    'youth.scanForMore': 'Scannez pour plus d\'infos',
    'youth.learnMore': 'En savoir plus sur l\'Avant-propos de la Jeunesse et les signataires',
    'youth.imfEstimates': 'Le FMI estime',
    'youth.imfAmount': '7,1 billions $/an',
    'youth.imfSubsidies': 'en subventions aux combustibles fossiles',
    'chapters.title': 'Chapitres',
    'chapters.subtitle': 'Un guide complet à travers 10 sujets essentiels',
    'chapter1.title': 'Fondamentaux du Changement Climatique',
    'chapter1.desc': 'Comprendre la science derrière le changement climatique, les gaz à effet de serre et pourquoi le rythme du changement compte.',
    'chapter2.title': 'Nature et Perte de Biodiversité',
    'chapter2.desc': 'Comment la biodiversité soutient les économies et les moyens de subsistance, et le besoin urgent de protection.',
    'chapter3.title': 'Pôles et Océans',
    'chapter3.desc': 'L\'Arctique et l\'Antarctique comme centres de contrôle climatique, et la triple menace qui pèse sur nos océans.',
    'chapter4.title': 'Adaptation',
    'chapter4.desc': 'Renforcer la résilience et limiter les dommages des impacts climatiques inévitables.',
    'chapter5.title': 'Finance Climatique',
    'chapter5.desc': 'Financer la transition: subventions, investissements et chemin vers le développement durable.',
    'chapter6.title': 'Économie du Changement Climatique',
    'chapter6.desc': 'Structures économiques, incitations et le vrai coût de l\'inaction.',
    'chapter7.title': 'Transition Énergétique, Transport et Industrie',
    'chapter7.desc': 'Transformer les secteurs clés pour un avenir bas carbone.',
    'chapter8.title': 'Alimentation, Forêts et Pêche',
    'chapter8.desc': 'Systèmes alimentaires durables et protection des écosystèmes vitaux.',
    'chapter9.title': 'COP – Vos Électeurs S\'en Soucient-ils?',
    'chapter9.desc': 'Coopération internationale, éducation climatique et lutte contre la désinformation.',
    'chapter10.title': 'Capture de Carbone et Marchés du Carbone',
    'chapter10.desc': 'Solutions technologiques et mécanismes de marché pour atteindre zéro net.',
    'stat.temperature': '1,5°C',
    'stat.temperature.label': 'Seuil de l\'Accord de Paris',
    'stat.subsidies': '7,1T$',
    'stat.subsidies.label': 'Subventions annuelles aux combustibles fossiles',
    'stat.support': '89%',
    'stat.support.label': 'Veulent plus d\'action climatique',
    'footer.attribution': 'Attribution des Chapitres',
    'footer.endorsers': 'Signataires de l\'Avant-propos Jeunesse',
    'footer.copyright': '© 2025 Guide Climatique des Parlementaires',
    'common.readMore': 'En Savoir Plus',
    'common.learnMore': 'Apprendre Plus',
    'common.keyFacts': 'Faits Clés',
    'common.takeAction': 'Agir',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.chapters': 'Kapitel',
    'nav.about': 'Über',
    'nav.download': 'PDF herunterladen',
    'hero.title': 'Der Globale Leitfaden für Parlamentarier zum Klimawandel und Klimalösungen',
    'hero.subtitle': 'Wesentliches Wissen für Entscheidungsträger in der Klimakrise',
    'hero.cta': 'Kapitel erkunden',
    'hero.scroll': 'Scrollen Sie, um mehr zu erfahren',
    'youth.title': 'Jugend-Vorwort',
    'youth.authoredBy': 'Jugend-Vorwort verfasst von',
    'youth.quote1': 'Als junge Menschen suchen wir oft bei unseren Älteren nach Orientierung. Von Ihnen entwickeln wir unsere Werte, unsere Ethik und unser Weltbild. Wir verdanken Ihnen unsere Chancen und Privilegien. Wir teilen Ihre Werte von Sicherheit, Wohlstand und Möglichkeiten.',
    'youth.quote2': 'Aber es ist eine seltsame Zeit, jung zu sein. "Geh zur Schule, finde einen Job, arbeite für deine Zukunft". Wir fragen uns, wie werden unsere Zukünfte aussehen?',
    'youth.content1': 'Die 1,5°C-Schwelle wird überschritten, 2,0°C nähert sich schnell. Wir fordern Sie auf, die von Ihnen gesetzten Klimaziele einzuhalten, transparent und rechenschaftspflichtig zu sein. Unsere Zukunft steht auf dem Spiel.',
    'youth.content2': 'Das menschliche Wohlbefinden hängt von der planetaren Gesundheit ab. Indigene Weisheiten haben seit Jahrtausenden den Glauben bewahrt, dass die Menschheit und die natürliche Welt eng verbunden sind. Unsere Zukunft hängt davon ab, diese alten Weisheiten mit modernen technologischen Fähigkeiten, Umweltverantwortung und einem entschlossenen politischen Willen zu verbinden.',
    'youth.content3': 'Die Wissenschaft ist klar. Die Technologien existieren. Die verbleibende Herausforderung ist ein Mangel an Umsetzung. Der IWF schätzt, dass es erstaunliche 7,1 Billionen Dollar pro Jahr an Subventionen für fossile Brennstoffe gibt. Wir brauchen neue wirtschaftliche Strukturen und Anreize, um globale Lösungen zu skalieren, und wir müssen jetzt handeln. Dies ist keine ferne Warnung mehr, wir leben im Zeitalter der Konsequenzen.',
    'youth.content4': 'Der Internationale Gerichtshof ist auf unserer Seite und bestätigt, was junge Menschen auf der ganzen Welt seit Jahren sagen: unsere Regierungen haben eine rechtliche Verpflichtung, gegen den Klimawandel zu handeln. Als aktuelle Führer und Entscheidungsträger brauchen wir Ihre mutige und authentische Führung, um dieses Zeitalter der Komplexität und Unsicherheit zu navigieren, um einen nachhaltigen Weg nach vorne zu zeichnen.',
    'youth.content5': 'Dies muss gemeinsam geschehen, über Disziplinen, Länder, Geschlechter und Generationen hinweg.',
    'youth.content6': 'Ein konkreter Schritt, den Parteien unternehmen können, um internationale Verpflichtungen mit intergenerationeller Gerechtigkeit in Einklang zu bringen, ist die Annahme der Universellen Jugendklausel in ihre aktualisierten national festgelegten Beiträge. Wir fordern alle Regierungen auf, unser Recht auf eine gesunde Umwelt und eine klimagerechte Zukunft für kommende Generationen zu ehren.',
    'youth.closingQuote': 'Als junge Menschen suchen wir oft bei unseren Älteren nach Orientierung. Wissen sie, dass sie auch zu uns aufschauen können?',
    'youth.endorsersNote': 'Unterstützer des Jugend-Vorworts finden Sie auf Seite 26.',
    'youth.scanForMore': 'Scannen für mehr Infos',
    'youth.learnMore': 'Mehr über das Jugend-Vorwort und Unterstützer erfahren',
    'youth.imfEstimates': 'Der IWF schätzt',
    'youth.imfAmount': '7,1 Billionen $/Jahr',
    'youth.imfSubsidies': 'an Subventionen für fossile Brennstoffe',
    'chapters.title': 'Kapitel',
    'chapters.subtitle': 'Ein umfassender Leitfaden durch 10 wesentliche Themen',
    'chapter1.title': 'Grundlagen des Klimawandels',
    'chapter1.desc': 'Die Wissenschaft hinter dem Klimawandel, Treibhausgase und warum die Änderungsrate wichtig ist.',
    'chapter2.title': 'Natur und Biodiversitätsverlust',
    'chapter2.desc': 'Wie Biodiversität Wirtschaften und Lebensgrundlagen stützt und die dringende Notwendigkeit des Schutzes.',
    'chapter3.title': 'Pole und Ozeane',
    'chapter3.desc': 'Die Arktis und Antarktis als Klimakontrollzentren und die dreifache Bedrohung unserer Ozeane.',
    'chapter4.title': 'Anpassung',
    'chapter4.desc': 'Resilienz aufbauen und Schäden durch unvermeidliche Klimaauswirkungen begrenzen.',
    'chapter5.title': 'Klimafinanzierung',
    'chapter5.desc': 'Die Transition finanzieren: Subventionen, Investitionen und der Weg zur nachhaltigen Entwicklung.',
    'chapter6.title': 'Die Ökonomie des Klimawandels',
    'chapter6.desc': 'Wirtschaftsstrukturen, Anreize und die wahren Kosten des Nichthandelns.',
    'chapter7.title': 'Energie-, Transport- und Industriewende',
    'chapter7.desc': 'Schlüsselsektoren für eine kohlenstoffarme Zukunft transformieren.',
    'chapter8.title': 'Ernährung, Wälder und Fischerei',
    'chapter8.desc': 'Nachhaltige Ernährungssysteme und der Schutz lebenswichtiger Ökosysteme.',
    'chapter9.title': 'COP – Interessieren sich Ihre Wähler?',
    'chapter9.desc': 'Internationale Zusammenarbeit, Klimabildung und Bekämpfung von Desinformation.',
    'chapter10.title': 'CO2-Abscheidung und Kohlenstoffmärkte',
    'chapter10.desc': 'Technologische Lösungen und Marktmechanismen zur Erreichung von Netto-Null.',
    'stat.temperature': '1,5°C',
    'stat.temperature.label': 'Pariser Abkommen Schwelle',
    'stat.subsidies': '7,1 Bio. $',
    'stat.subsidies.label': 'Jährliche Subventionen für fossile Brennstoffe',
    'stat.support': '89%',
    'stat.support.label': 'Wollen mehr Klimaschutz',
    'footer.attribution': 'Kapitel-Zuordnung',
    'footer.endorsers': 'Unterstützer des Jugend-Vorworts',
    'footer.copyright': '© 2025 Parlamentarier-Klimaleitfaden',
    'common.readMore': 'Mehr lesen',
    'common.learnMore': 'Mehr erfahren',
    'common.keyFacts': 'Wichtige Fakten',
    'common.takeAction': 'Handeln',
  },
  zh: {
    'nav.home': '首页',
    'nav.chapters': '章节',
    'nav.about': '关于',
    'nav.download': '下载PDF',
    'hero.title': '议员全球气候变化与气候解决方案指南',
    'hero.subtitle': '政策制定者应对气候危机的必备知识',
    'hero.cta': '探索章节',
    'hero.scroll': '滚动了解更多',
    'youth.title': '青年前言',
    'youth.authoredBy': '青年前言作者',
    'youth.quote1': '作为年轻人，我们经常向长辈寻求指导。从您那里，我们发展我们的价值观、我们的道德和我们的世界观。我们的机会和特权归功于您。我们分享您对安全、繁荣和机会的价值观。',
    'youth.quote2': '但这是一个奇怪的年轻时代。"去上学，找工作，为未来努力"。我们想知道，我们的未来会是什么样子？',
    'youth.content1': '1.5°C的门槛正在被突破，2.0°C正在快速逼近。我们呼吁您兑现您设定的气候目标，保持透明和负责任。我们的未来岌岌可危。',
    'youth.content2': '人类福祉取决于地球健康。土著智慧千百年来一直认为人类与自然世界紧密相连。我们的未来取决于将这些古老智慧与现代技术能力、环境管理和坚定的政治意愿相结合。',
    'youth.content3': '科学是明确的。技术已经存在。剩下的挑战是缺乏实施。国际货币基金组织估计，每年有惊人的7.1万亿美元用于化石燃料补贴。我们需要新的经济结构和激励措施来扩大全球解决方案，我们需要现在就行动。这不再是遥远的警告，我们正生活在后果的时代。',
    'youth.content4': '国际法院站在我们这边，肯定了全球年轻人多年来一直在说的话：我们的政府有法律义务对气候变化采取行动。作为当前的领导人和决策者，我们需要您勇敢和真诚的领导来驾驭这个复杂和不确定的时代，开辟一条可持续的前进道路。',
    'youth.content5': '这必须共同完成，跨越学科、国家、性别和世代。',
    'youth.content6': '各方可以采取的一个具体步骤是将普遍青年条款纳入其更新的国家自主贡献，以使国际承诺与代际正义保持一致。我们呼吁所有政府尊重我们享有健康环境和气候公正未来的权利，为子孙后代。',
    'youth.closingQuote': '作为年轻人，我们经常向长辈寻求指导。他们知道他们也可以向我们寻求帮助吗？',
    'youth.endorsersNote': '青年前言的支持者可在第26页找到。',
    'youth.scanForMore': '扫描获取更多信息',
    'youth.learnMore': '了解更多关于青年前言和支持者',
    'youth.imfEstimates': '国际货币基金组织估计',
    'youth.imfAmount': '7.1万亿美元/年',
    'youth.imfSubsidies': '化石燃料补贴',
    'chapters.title': '章节',
    'chapters.subtitle': '涵盖10个基本主题的综合指南',
    'chapter1.title': '气候变化基础知识',
    'chapter1.desc': '了解气候变化背后的科学、温室气体以及变化速率的重要性。',
    'chapter2.title': '自然与生物多样性丧失',
    'chapter2.desc': '生物多样性如何支撑经济和生计，以及保护的迫切需要。',
    'chapter3.title': '极地与海洋',
    'chapter3.desc': '北极和南极作为气候控制中心，以及海洋面临的三重威胁。',
    'chapter4.title': '适应',
    'chapter4.desc': '建立韧性并限制不可避免的气候影响造成的损害。',
    'chapter5.title': '气候融资',
    'chapter5.desc': '为转型提供资金：补贴、投资和可持续发展之路。',
    'chapter6.title': '气候变化经济学',
    'chapter6.desc': '经济结构、激励措施和不作为的真正代价。',
    'chapter7.title': '能源、交通和工业转型',
    'chapter7.desc': '为低碳未来转型关键部门。',
    'chapter8.title': '食品、森林和渔业',
    'chapter8.desc': '可持续食品系统和重要生态系统的保护。',
    'chapter9.title': 'COP——您的选民关心吗？',
    'chapter9.desc': '国际合作、气候教育和打击虚假信息。',
    'chapter10.title': '碳捕获和碳市场',
    'chapter10.desc': '实现净零的技术解决方案和市场机制。',
    'stat.temperature': '1.5°C',
    'stat.temperature.label': '巴黎协定门槛',
    'stat.subsidies': '7.1万亿美元',
    'stat.subsidies.label': '年度化石燃料补贴',
    'stat.support': '89%',
    'stat.support.label': '希望采取更多气候行动',
    'footer.attribution': '章节归属',
    'footer.endorsers': '青年前言背书者',
    'footer.copyright': '© 2025 议员气候指南',
    'common.readMore': '阅读更多',
    'common.learnMore': '了解更多',
    'common.keyFacts': '关键事实',
    'common.takeAction': '采取行动',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.chapters': 'الفصول',
    'nav.about': 'حول',
    'nav.download': 'تحميل PDF',
    'hero.title': 'دليل البرلمانيين العالمي لتغير المناخ والحلول المناخية',
    'hero.subtitle': 'المعرفة الأساسية لصانعي السياسات في مواجهة أزمة المناخ',
    'hero.cta': 'استكشف الفصول',
    'hero.scroll': 'مرر لمعرفة المزيد',
    'youth.title': 'تمهيد الشباب',
    'youth.authoredBy': 'تمهيد الشباب من تأليف',
    'youth.quote1': 'كشباب، غالبًا ما نتطلع إلى كبارنا للحصول على التوجيه. منكم نطور قيمنا وأخلاقنا ورؤيتنا للعالم. نحن مدينون لكم بفرصنا وامتيازاتنا. نتشارك قيمكم في الأمن والازدهار والفرص.',
    'youth.quote2': 'لكنه وقت غريب لتكون شابًا. "اذهب إلى المدرسة، احصل على وظيفة، اعمل من أجل مستقبلك". نتساءل، كيف ستبدو مستقبلاتنا؟',
    'youth.content1': 'عتبة 1.5 درجة مئوية تُتجاوز، و2.0 درجة مئوية تقترب بسرعة. ندعوكم للوفاء بأهداف المناخ التي وضعتموها، وأن تكونوا شفافين ومسؤولين. مستقبلنا على المحك.',
    'youth.content2': 'رفاهية الإنسان تعتمد على صحة الكوكب. حافظت الحكم الأصلية لآلاف السنين على الإيمان بأن البشرية والعالم الطبيعي مرتبطان ارتباطًا وثيقًا. تعتمد مستقبلاتنا على الجمع بين هذه الحكم القديمة والقدرات التكنولوجية الحديثة والإشراف البيئي والإرادة السياسية الحاسمة.',
    'youth.content3': 'العلم واضح. التقنيات موجودة. التحدي المتبقي هو نقص التنفيذ. يقدر صندوق النقد الدولي أن هناك 7.1 تريليون دولار سنويًا مذهلة في دعم الوقود الأحفوري. نحتاج إلى هياكل اقتصادية وحوافز جديدة لتوسيع الحلول العالمية، ونحتاج للتصرف الآن. هذا لم يعد تحذيرًا بعيدًا، نحن نعيش في عصر العواقب.',
    'youth.content4': 'محكمة العدل الدولية إلى جانبنا، مؤكدة ما كان الشباب في جميع أنحاء العالم يقولونه لسنوات: حكوماتنا لديها التزام قانوني بالتصرف بشأن تغير المناخ. بصفتكم القادة وصانعي السياسات الحاليين، نحتاج إلى قيادتكم الشجاعة والأصيلة للتنقل في عصر التعقيد وعدم اليقين هذا، لرسم مسار مستدام للأمام.',
    'youth.content5': 'يجب أن يتم ذلك معًا، عبر التخصصات والبلدان والأجناس والأجيال.',
    'youth.content6': 'خطوة ملموسة يمكن للأطراف اتخاذها لمواءمة الالتزامات الدولية مع العدالة بين الأجيال هي اعتماد بند الشباب العالمي في مساهماتهم المحددة وطنيًا المحدثة. ندعو جميع الحكومات لاحترام حقنا في بيئة صحية ومستقبل مناخي عادل للأجيال القادمة.',
    'youth.closingQuote': 'كشباب، غالبًا ما نتطلع إلى كبارنا للحصول على التوجيه. هل يعلمون أنهم يستطيعون التطلع إلينا أيضًا؟',
    'youth.endorsersNote': 'يمكن العثور على مؤيدي تمهيد الشباب في الصفحة 26.',
    'youth.scanForMore': 'امسح لمزيد من المعلومات',
    'youth.learnMore': 'تعرف على المزيد حول تمهيد الشباب والمؤيدين',
    'youth.imfEstimates': 'يقدر صندوق النقد الدولي',
    'youth.imfAmount': '7.1 تريليون دولار/سنة',
    'youth.imfSubsidies': 'في دعم الوقود الأحفوري',
    'chapters.title': 'الفصول',
    'chapters.subtitle': 'دليل شامل عبر 10 مواضيع أساسية',
    'chapter1.title': 'أساسيات تغير المناخ',
    'chapter1.desc': 'فهم العلم وراء تغير المناخ والغازات الدفيئة ولماذا يهم معدل التغيير.',
    'chapter2.title': 'الطبيعة وفقدان التنوع البيولوجي',
    'chapter2.desc': 'كيف يدعم التنوع البيولوجي الاقتصادات وسبل العيش، والحاجة الملحة للحماية.',
    'chapter3.title': 'القطبان والمحيطات',
    'chapter3.desc': 'القطب الشمالي والجنوبي كمراكز للتحكم في المناخ، والتهديد الثلاثي الذي تواجهه محيطاتنا.',
    'chapter4.title': 'التكيف',
    'chapter4.desc': 'بناء المرونة والحد من الأضرار الناجمة عن آثار المناخ الحتمية.',
    'chapter5.title': 'التمويل المناخي',
    'chapter5.desc': 'تمويل التحول: الإعانات والاستثمارات والطريق نحو التنمية المستدامة.',
    'chapter6.title': 'اقتصاديات تغير المناخ',
    'chapter6.desc': 'الهياكل الاقتصادية والحوافز والتكلفة الحقيقية للتقاعس.',
    'chapter7.title': 'تحول الطاقة والنقل والصناعة',
    'chapter7.desc': 'تحويل القطاعات الرئيسية لمستقبل منخفض الكربون.',
    'chapter8.title': 'الغذاء والغابات ومصايد الأسماك',
    'chapter8.desc': 'أنظمة غذائية مستدامة وحماية النظم البيئية الحيوية.',
    'chapter9.title': 'COP - هل يهتم ناخبوك؟',
    'chapter9.desc': 'التعاون الدولي والتثقيف المناخي ومكافحة المعلومات المضللة.',
    'chapter10.title': 'احتجاز الكربون وأسواق الكربون',
    'chapter10.desc': 'الحلول التقنية وآليات السوق لتحقيق صافي الصفر.',
    'stat.temperature': '1.5°م',
    'stat.temperature.label': 'عتبة اتفاقية باريس',
    'stat.subsidies': '7.1 تريليون دولار',
    'stat.subsidies.label': 'دعم الوقود الأحفوري السنوي',
    'stat.support': '89%',
    'stat.support.label': 'يريدون المزيد من العمل المناخي',
    'footer.attribution': 'إسناد الفصول',
    'footer.endorsers': 'مؤيدو تمهيد الشباب',
    'footer.copyright': '© 2025 دليل البرلمانيين للمناخ',
    'common.readMore': 'اقرأ المزيد',
    'common.learnMore': 'تعرف على المزيد',
    'common.keyFacts': 'حقائق رئيسية',
    'common.takeAction': 'اتخذ إجراء',
  },
  pt: {
    'nav.home': 'Início',
    'nav.chapters': 'Capítulos',
    'nav.about': 'Sobre',
    'nav.download': 'Baixar PDF',
    'hero.title': 'Guia Global dos Parlamentares sobre Mudanças Climáticas e Soluções Climáticas',
    'hero.subtitle': 'Conhecimento essencial para formuladores de políticas enfrentando a crise climática',
    'hero.cta': 'Explorar Capítulos',
    'hero.scroll': 'Role para saber mais',
    'youth.title': 'Prefácio da Juventude',
    'youth.authoredBy': 'Prefácio da Juventude escrito por',
    'youth.quote1': 'Como jovens, frequentemente olhamos para nossos anciãos em busca de orientação. De vocês, desenvolvemos nossos valores, nossa ética e nossa visão de mundo. Devemos a vocês nossas oportunidades e privilégios. Compartilhamos seus valores de segurança, prosperidade e oportunidade.',
    'youth.quote2': 'Mas é um momento estranho para ser jovem. "Vá para a escola, arrume um emprego, trabalhe para o seu futuro". Nos perguntamos, como serão nossos futuros?',
    'youth.content1': 'O limite de 1,5°C está sendo ultrapassado, 2,0°C está se aproximando rapidamente. Pedimos que cumpram as metas climáticas estabelecidas, que sejam transparentes e responsáveis. Nossos futuros estão em jogo.',
    'youth.content2': 'O bem-estar humano depende da saúde planetária. As sabedorias indígenas mantiveram por milênios a crença de que a humanidade e o mundo natural estão intimamente conectados. Nossos futuros dependem de combinar essas sabedorias antigas com capacidades tecnológicas modernas, gestão ambiental e uma vontade política decisiva.',
    'youth.content3': 'A ciência é clara. As tecnologias existem. O desafio que resta é a falta de implementação. O FMI estima que há espantosos US$ 7,1 trilhões por ano em subsídios a combustíveis fósseis. Precisamos de novas estruturas econômicas e incentivos para escalar soluções globais, e precisamos agir agora. Isso não é mais um aviso distante, estamos vivendo na era das consequências.',
    'youth.content4': 'A Corte Internacional de Justiça está do nosso lado, afirmando o que os jovens em todo o mundo têm dito há anos: nossos governos têm a obrigação legal de agir sobre as mudanças climáticas. Como líderes e formuladores de políticas atuais, precisamos de sua liderança corajosa e autêntica para navegar esta era de complexidade e incerteza, para traçar um caminho sustentável adiante.',
    'youth.content5': 'Isso deve ser feito juntos, através de disciplinas, países, gêneros e gerações.',
    'youth.content6': 'Um passo concreto que as partes podem dar para alinhar compromissos internacionais com justiça intergeracional é adotar a Cláusula Universal da Juventude em suas Contribuições Nacionalmente Determinadas atualizadas. Pedimos a todos os governos que honrem nosso direito a um ambiente saudável e um futuro climático justo para as gerações vindouras.',
    'youth.closingQuote': 'Como jovens, frequentemente olhamos para nossos anciãos em busca de orientação. Eles sabem que podem olhar para nós também?',
    'youth.endorsersNote': 'Os apoiadores do Prefácio da Juventude podem ser encontrados na página 26.',
    'youth.scanForMore': 'Escaneie para mais informações',
    'youth.learnMore': 'Saiba mais sobre o Prefácio da Juventude e apoiadores',
    'youth.imfEstimates': 'O FMI estima',
    'youth.imfAmount': 'US$ 7,1 trilhões/ano',
    'youth.imfSubsidies': 'em subsídios a combustíveis fósseis',
    'chapters.title': 'Capítulos',
    'chapters.subtitle': 'Um guia abrangente através de 10 tópicos essenciais',
    'chapter1.title': 'Fundamentos das Mudanças Climáticas',
    'chapter1.desc': 'Entendendo a ciência por trás das mudanças climáticas, gases de efeito estufa e por que a taxa de mudança importa.',
    'chapter2.title': 'Natureza e Perda de Biodiversidade',
    'chapter2.desc': 'Como a biodiversidade sustenta economias e meios de vida, e a necessidade urgente de proteção.',
    'chapter3.title': 'Polos e Oceanos',
    'chapter3.desc': 'O Ártico e a Antártida como centros de controle climático, e a tripla ameaça aos nossos oceanos.',
    'chapter4.title': 'Adaptação',
    'chapter4.desc': 'Construindo resiliência e limitando danos dos impactos climáticos inevitáveis.',
    'chapter5.title': 'Financiamento Climático',
    'chapter5.desc': 'Financiando a transição: subsídios, investimentos e o caminho para o desenvolvimento sustentável.',
    'chapter6.title': 'A Economia das Mudanças Climáticas',
    'chapter6.desc': 'Estruturas econômicas, incentivos e o verdadeiro custo da inação.',
    'chapter7.title': 'Transição de Energia, Transporte e Indústria',
    'chapter7.desc': 'Transformando setores-chave para um futuro de baixo carbono.',
    'chapter8.title': 'Alimentos, Florestas e Pesca',
    'chapter8.desc': 'Sistemas alimentares sustentáveis e proteção de ecossistemas vitais.',
    'chapter9.title': 'COP – Seus Eleitores Se Importam?',
    'chapter9.desc': 'Cooperação internacional, educação climática e combate à desinformação.',
    'chapter10.title': 'Captura de Carbono e Mercados de Carbono',
    'chapter10.desc': 'Soluções tecnológicas e mecanismos de mercado para alcançar emissões líquidas zero.',
    'stat.temperature': '1,5°C',
    'stat.temperature.label': 'Limite do Acordo de Paris',
    'stat.subsidies': 'US$ 7,1 tri',
    'stat.subsidies.label': 'Subsídios anuais a combustíveis fósseis',
    'stat.support': '89%',
    'stat.support.label': 'Querem mais ação climática',
    'footer.attribution': 'Atribuição dos Capítulos',
    'footer.endorsers': 'Apoiadores do Prefácio da Juventude',
    'footer.copyright': '© 2025 Guia Climático dos Parlamentares',
    'common.readMore': 'Leia Mais',
    'common.learnMore': 'Saiba Mais',
    'common.keyFacts': 'Fatos-Chave',
    'common.takeAction': 'Agir',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.chapters': 'Главы',
    'nav.about': 'О нас',
    'nav.download': 'Скачать PDF',
    'hero.title': 'Глобальное руководство парламентариев по изменению климата и климатическим решениям',
    'hero.subtitle': 'Необходимые знания для политиков, решающих климатический кризис',
    'hero.cta': 'Изучить главы',
    'hero.scroll': 'Прокрутите, чтобы узнать больше',
    'youth.title': 'Предисловие молодёжи',
    'youth.authoredBy': 'Предисловие молодёжи написано',
    'youth.quote1': 'Как молодые люди, мы часто обращаемся к старшим за советом. От вас мы развиваем наши ценности, нашу этику и наше мировоззрение. Мы обязаны вам нашими возможностями и привилегиями. Мы разделяем ваши ценности безопасности, процветания и возможностей.',
    'youth.quote2': 'Но странное время быть молодым. "Ходи в школу, найди работу, работай на своё будущее". Мы задаёмся вопросом, как будет выглядеть наше будущее?',
    'youth.content1': 'Порог в 1,5°C превышается, 2,0°C быстро приближается. Мы призываем вас выполнить поставленные климатические цели, быть прозрачными и подотчётными. Наше будущее под угрозой.',
    'youth.content2': 'Благополучие человека зависит от здоровья планеты. Мудрость коренных народов тысячелетиями хранила убеждение, что человечество и природный мир тесно связаны. Наше будущее зависит от сочетания этих древних мудростей с современными технологическими возможностями, экологическим управлением и решительной политической волей.',
    'youth.content3': 'Наука ясна. Технологии существуют. Оставшаяся проблема — отсутствие реализации. МВФ оценивает, что существует поразительные 7,1 триллиона долларов в год субсидий на ископаемое топливо. Нам нужны новые экономические структуры и стимулы для масштабирования глобальных решений, и нам нужно действовать сейчас. Это больше не далёкое предупреждение, мы живём в эпоху последствий.',
    'youth.content4': 'Международный суд на нашей стороне, подтверждая то, что молодые люди по всему миру говорили годами: наши правительства имеют юридическое обязательство действовать в отношении изменения климата. Как нынешние лидеры и политики, нам нужно ваше смелое и подлинное лидерство, чтобы ориентироваться в эту эпоху сложности и неопределённости, чтобы проложить устойчивый путь вперёд.',
    'youth.content5': 'Это должно быть сделано вместе, через дисциплины, страны, гендеры и поколения.',
    'youth.content6': 'Один конкретный шаг, который стороны могут предпринять для согласования международных обязательств с межпоколенческой справедливостью — это принять Универсальную молодёжную оговорку в свои обновлённые национально определённые вклады. Мы призываем все правительства уважать наше право на здоровую окружающую среду и климатически справедливое будущее для грядущих поколений.',
    'youth.closingQuote': 'Как молодые люди, мы часто обращаемся к старшим за советом. Знают ли они, что могут обращаться и к нам тоже?',
    'youth.endorsersNote': 'Поддержавших предисловие молодёжи можно найти на странице 26.',
    'youth.scanForMore': 'Сканируйте для получения информации',
    'youth.learnMore': 'Узнайте больше о предисловии молодёжи и поддержавших',
    'youth.imfEstimates': 'МВФ оценивает',
    'youth.imfAmount': '7,1 триллиона $/год',
    'youth.imfSubsidies': 'субсидий на ископаемое топливо',
    'chapters.title': 'Главы',
    'chapters.subtitle': 'Полное руководство по 10 основным темам',
    'chapter1.title': 'Основы изменения климата',
    'chapter1.desc': 'Понимание науки об изменении климата, парниковых газах и почему важна скорость изменений.',
    'chapter2.title': 'Природа и утрата биоразнообразия',
    'chapter2.desc': 'Как биоразнообразие поддерживает экономику и средства к существованию, и острая необходимость защиты.',
    'chapter3.title': 'Полюса и океаны',
    'chapter3.desc': 'Арктика и Антарктика как центры управления климатом, и тройная угроза нашим океанам.',
    'chapter4.title': 'Адаптация',
    'chapter4.desc': 'Повышение устойчивости и ограничение ущерба от неизбежных климатических воздействий.',
    'chapter5.title': 'Климатическое финансирование',
    'chapter5.desc': 'Финансирование перехода: субсидии, инвестиции и путь к устойчивому развитию.',
    'chapter6.title': 'Экономика изменения климата',
    'chapter6.desc': 'Экономические структуры, стимулы и истинная цена бездействия.',
    'chapter7.title': 'Переход в энергетике, транспорте и промышленности',
    'chapter7.desc': 'Трансформация ключевых секторов для низкоуглеродного будущего.',
    'chapter8.title': 'Продовольствие, леса и рыболовство',
    'chapter8.desc': 'Устойчивые продовольственные системы и защита жизненно важных экосистем.',
    'chapter9.title': 'COP – Волнует ли это ваших избирателей?',
    'chapter9.desc': 'Международное сотрудничество, климатическое образование и борьба с дезинформацией.',
    'chapter10.title': 'Улавливание углерода и углеродные рынки',
    'chapter10.desc': 'Технологические решения и рыночные механизмы для достижения нулевых выбросов.',
    'stat.temperature': '1,5°C',
    'stat.temperature.label': 'Порог Парижского соглашения',
    'stat.subsidies': '$7,1 трлн',
    'stat.subsidies.label': 'Ежегодные субсидии на ископаемое топливо',
    'stat.support': '89%',
    'stat.support.label': 'Хотят больше климатических действий',
    'footer.attribution': 'Авторство глав',
    'footer.endorsers': 'Поддержавшие молодёжное предисловие',
    'footer.copyright': '© 2025 Климатическое руководство парламентариев',
    'common.readMore': 'Читать далее',
    'common.learnMore': 'Узнать больше',
    'common.keyFacts': 'Ключевые факты',
    'common.takeAction': 'Действовать',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  zh: '中文',
  ar: 'العربية',
  pt: 'Português',
  ru: 'Русский',
};